### ISSUE TITLE
Usage within React Native apps

### ISSUE THREAD

**Issue by Yorik0512** [mattrglobal/jsonld-signatures-bbs#188] opened 2022-06-11 10:43 UTC
Hey guys,

You still refer to asm.js as a fallback for cases like React Native, although asm.js support was removed in May 2021.

Could you please point me to the solution that shall help me to apply this library within our React Native app?

I would appreciate any piece of advice to help in advancing towards the solution in case it’s not available at the moment.

Regards,
Yurii

**Comment by tplooker** [comment] 2022-09-14 20:48
Hi @Yorik0512, bbs-signatures is WASM based which all major browsers support so the library works with web based frameworks out of the box.

**Comment by nklomp** [comment] 2022-09-20 19:40
@tplooker React-Native is not browser based, you are probably confusing it with React.

Actually I am also interested in how React-Native would be supported, now that asm.js has been removed altogether.

**Comment by tplooker** [comment] 2022-12-18 22:29
Duplicate of #177, closing in favour of that issue.

> React-Native is not browser based, you are probably confusing it with React.

Yes you are correct, I miss read this issue, React Native because it does not have WASM support requires native wrapping, we provide android and ios wrappers [here](https://github.com/mattrglobal/ffi-bbs-signatures) that can then be surfaced in to an RN library.

**Closed** 2022-12-18 22:29 UTC
